wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1670461992.0557
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.13.5
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 128
dataset:
  desc: null
  value: /home/ishii/graduation_research/MAT-master/data/wavelength/smiles_wavelength.csv
dropout:
  desc: null
  value: 0.2
embedding_dim:
  desc: null
  value: 128
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.001
lstm_size:
  desc: null
  value: 128
num_layers:
  desc: null
  value: 3
